name: KSDOS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar NASM
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: Rodar Compilação
        run: make

      - name: Upload Artefato
        uses: actions/upload-artifact@v4
        with:
          name: ksdos-image
          path: build/ksdos.img

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/ksdos.img
          body: "Nova build do KSDOS gerada automaticamente."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


